# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:


name: gefs_osn

jobs:
  docker:
    runs-on: ubuntu-latest #[self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container: rocker/geospatial:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          remotes::install_github("eco4cast/gefs4cast")

      - name: Download stage 1
        shell: Rscript {0}
        run: |
          source("download_stage1.R")

      - name: Generate stage 2
        shell: Rscript {0}
        run: |
          source("generate_stage2.R")

      - name: Healthcheck
      #  run: |
      #    curl -m 10 --retry 5 https://hc-ping.com/fc148462-2f07-4cd3-a11d-823982db0270