on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast:dev-osgeo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          # set the shinyapps keys as environment variables
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.eeZw3a65bFn }}
        run: /usr/local/bin/r stage1.R
